### ISSUE TITLE
Missing Monitor functionality?

### ISSUE THREAD

**Issue by matkuki** [nimgl/nimgl#21]
Hi,

I see that a few __GLFWMonitor__ procedures/types are missing like:
- type _GLFWvidmode_
- procedure _glfwGetVideoMode_
- most of the other stuff from: https://www.glfw.org/docs/latest/group__monitor.html

What I need is to get the current monitor resolution, is there another to way to get this?

Thanks,
Matic

**Comment by lmariscal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GLFW is missing monitor functionality.](https://trello.com/c/jvmtwPst/1-glfw-is-missing-monitor-functionality)
