### ISSUE TITLE
Cimgui 1.70 (and later?) export igMenuItemBool (and igMenuItemBoolPtr)

### ISSUE THREAD

**Issue by kraptor** [nimgl/nimgl#23]
https://github.com/nimgl/nimgl/blob/11e7767145d7640311cabc9a846d8a12a31379f1/src/nimgl/imgui.nim#L1584

I fixed it in my local copy by referencing the proper symbol:

`proc igMenuItem*(label: cstring, shortcut: cstring = nil, selected: bool = false, enabled: bool = true): bool {.imgui_lib, importc: "igMenuItemBool".}`

**Comment by lmariscal** [comment]
Fixed on https://github.com/nimgl/nimgl/issues/22 and https://github.com/nimgl/nimgl/commit/dae491c1b40d72c9df245edabf0080bfb5139b64.

**Comment by kraptor** [comment]
You are awesome, thanks!
