### ISSUE TITLE
STB compilation fails if spaces in include path

### ISSUE THREAD

**Issue by strexicious** [nimgl/nimgl#27]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**
Fails to compile STB because there was a space in the path to STB (observed in the linked image). Note this occurs only when I try to `import nimgl/[glfw, opengl]` and nimgl installation itself was succesful.
![image](https://user-images.githubusercontent.com/13009365/63060268-0d89ab80-bef2-11e9-86b9-23b5b2c3f85a.png)

* **What is the expected behavior?**
That it is able to correctly use paths with spaces.

* **Please tell us about your environment:**
  
  - Version: 0.3.6
  - OS: Windows
  - Bindings: Using OpenGL and GLFW.
  - Backend: Default C

* **Other information**
https://github.com/nimgl/nimgl/blob/master/src/nimgl/stb/image.nim
I think the error is traced to line 15 of the above file, and maybe (escape) quoting the path might fix this issue.

**Comment by strexicious** [comment]
Actually just went ahead and applied the proposed fix above and I was able to successfully install and use my local fork with the fix. Should I open a PR from https://github.com/strexicious/nimgl/tree/stb_path_fix ?

**Comment by lmariscal** [comment]
Please create the fork. And thank you for creating the fix!

As a side note, version 1.0 (still in development) doesn't use anymore stb to parse the icon in GLFW.
