### ISSUE TITLE
OpenGL incorrectly declared as a cast (instead of a literal)

### ISSUE THREAD

**Issue by kraptor** [nimgl/nimgl#29]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**

* **What is the expected behavior?**
GL_TIMEOUT_IGNORED
GK_TIMEOUT_IGNORED_APPLE

should have valid values.

* **What is the motivation / use case for changing the behavior?**

Nim 1.0 doesn't allow ```uint64(0xFFFFFFFFFFFFFFFF)```

Instead, used this:
  GL_TIMEOUT_IGNORED*: uint64 = 0xFFFFFFFFFFFFFFFF'u64
  GL_TIMEOUT_IGNORED_APPLE*: uint64 = 0xFFFFFFFFFFFFFFFF'u64

* **Please tell us about your environment:**
  
  - Version: [1.0.0 ]
  - OS: [ Windows]
  - Bindings: [ OpenGL]
  - Backend: [ C  and CPP ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
suggestions how to fix, links for us to have context, eg. stackoverflow,
docs.gl, documentation etc)

This seems an issue with Nim 1.0, with prev version was working correctly.

**Comment by kraptor** [comment]
I'm not sure where to fix this, the other repo seems archived. Please, provide feedback. Thanks!

**Comment by lmariscal** [comment]
Oh, we both saw the same issue at the same time haha. I think your fix is cleaner than mine so I will change it in short and I forgot to change the enums.

PD: Sorry if the commits have been slow, most of my work has gone into the thesis document instead of the repo. This should change in the near future.

**Comment by kraptor** [comment]
It's ok mate, I understand. We are all upgrading to 1.0 and catching errors end so on... haha.

**Comment by lmariscal** [comment]
Fixed by https://github.com/nimgl/nimgl/commit/75c5fc89e9274b10d0a228b0f925639b7a250211 for 0.3 and https://github.com/nimgl/nimgl/commit/ced8c00761aa9a1214e795541703c6103e2c2cf3 for 1.0.

Need to rewrite opengl generator but atm a quick fix in the code should be fine.
