### ISSUE TITLE
Constant definition error

### ISSUE THREAD

**Issue by matkuki** [nimgl/nimgl#30]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **What is the current behavior?**
importing nimgl throws this during compilation:
```bash
C:\...\.nimble\pkgs\nimgl-0.3.6\nimgl\opengl.nim(69, 39) Error: -1 can't be converted to uint64
```

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**
Just importing `nimgl` creates the error

* **Please tell us about your environment:**
  
  - Version: [ nimgl 0.3.6 | Nim 1.0.99 [Windows: amd64] ]
  - OS: [ Windows ]
  - Bindings: [ GLFW ]
  - Backend: [ C ]

**Comment by skellock** [comment]
```nim
requires "nimgl >= 1.0.0"
```

Backstory [here](https://github.com/nimgl/nimgl/issues/29).

**Comment by lmariscal** [comment]
But I did promise to give support to 0.3 so I will be fixing this issue shortly.
