### ISSUE TITLE
GLFW: Getting the width and height of the screen problem

### ISSUE THREAD

**Issue by matkuki** [nimgl/nimgl#31]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
My old code used to work to get the width and height of the current screen with, but now it shows weird numbers:
```nim
var monitor = glfwGetPrimaryMonitor()
var videoMode = getVidMode(monitor)
echo videoMode.width # This shows "6945968"
echo videoMode.height # This shows "0"
```
So I tried using `getMonitorWorkarea`, but this code:
```nim
monitor = glfwGetPrimaryMonitor()
var x, y, width, height: int32
monitor.getMonitorWorkarea(x, y, width, height)
```
throws this error during the link stage of C compilation:
```bash
C:\...\nimcache\impulse_engine_d\@mimpulse_engine.nim.c.o:@mimpulse_engine.nim.c:(.text+0x1ebc): undefined reference to `glfwGetMonitorWorkarea'
collect2.exe: error: ld returned 1 exit status
```

* **What is the expected behavior?**
Either the `videoMode.width` and `videoMode.width` should show the correct values or `getMonitorWorkarea` should compile and work as expected.

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - OS: Windows
  - Bindings: OpenGL | GLFW
  - Backend: C

**Comment by lmariscal** [comment]
Okay, the second issue is my fault since I didn't read that that specific function is available since 3.3 and the library still doesn't support it https://github.com/nimgl/nimgl/issues/7. The first issue does have me wondering where the issue in my code is since the definition of GLFWVidMode is:
```nim
  GLFWVidMode* = object
    ## This describes a single video mode.
    width*: int32
    height*: int32
    redBits*: int32
    greenBits*: int32
    blueBits*: int32
    refreshRate*: int32
```
and the GLFW one is (in the one imported):
```c
typedef struct GLFWvidmode
{
    /*! The width, in screen coordinates, of the video mode.
     */
    int width;
    /*! The height, in screen coordinates, of the video mode.
     */
    int height;
    /*! The bit depth of the red channel of the video mode.
     */
    int redBits;
    /*! The bit depth of the green channel of the video mode.
     */
    int greenBits;
    /*! The bit depth of the blue channel of the video mode.
     */
    int blueBits;
    /*! The refresh rate, in Hz, of the video mode.
     */
    int refreshRate;
} GLFWvidmode;
```

I am currently working in the generator for GLFW (started yesterday) will do my best to have it ASAP. I hope it fixes problem one (two should be a guarantee) if not I will start debugging the data.

**Comment by lmariscal** [comment]
Yeah, found the issue. The returned value is a pointer .-. (big mistake by me) added a ptr value and it should be fixed will be pushing shortly. Still will have that generator ASAP so you don't have to rewrite too much code.

**Comment by lmariscal** [comment]
https://github.com/nimgl/nimgl/commit/763407463c566087ba40936e0b5dd18b08aa17f6 should fix your issue. I will not be closing this issue until the new generator is done though.

**Comment by matkuki** [comment]
I tested it again and am confirming that it works now.
Thanks

**Comment by lmariscal** [comment]
Pushed https://github.com/nimgl/nimgl/commit/6f81c7c3a5fc60be8916e2edacb94c31d05dd321 the rewrite of GLFW version 3.3 it includes `getMonitorWorkarea`. Closing this issue.
