### ISSUE TITLE
glTexParameteri/glTexImage2D  function signatures expect GL_LINEAR/GL_RGBA as GLint but these are declared as GLenum

### ISSUE THREAD

**Issue by deepakg** [nimgl/nimgl#32]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Unable to compile

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**
I am translating the following example from the original imgui documentation to nim:
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
(See under the section: Example for OpenGL Users)

My code:
```
import nimgl/imgui, nimgl/imgui/[impl_opengl, impl_glfw]
import nimgl/[opengl, glfw]
import nimgl/stb/image

proc loadImage(out_texture: var GLuint, width: var int32, height: var int32) =
  var image_width: int32 = 0
  var image_height: int32  = 0
  var image_data = stbi_load("/Users/deepakg/proj/test.png", image_width.addr, image_height.addr, nil, 4)
  echo(image_width, ",", image_height)

  var image_texture: GLuint
  glGenTextures(1, image_texture.addr)
  glBindTexture(GL_TEXTURE_2D, image_texture)
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR)


  glPixelStorei(GL_UNPACK_ROW_LENGTH, 0)
  glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data)
  stbi_image_free(image_data);
  width = image_width
  height = image_height
  out_texture = image_texture

  echo("Image_texture: ", image_texture)
```
I get a couple of compiler errors. First with:

```
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR)
```

```
Error: type mismatch: got <GLenum, GLenum, GLenum>
but expected one of: 
proc glTexParameteri(target: GLenum; pname: GLenum; param: GLint): void
  first type mismatch at position: 3
  required type for param: GLint
  but expression '9729'u' is of type: GLenum
```

and then with:

```
glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, image_width, image_height, 0, GL_RGBA, GL_UNSIGNED_BYTE, image_data)
```

```
 Error: type mismatch: got <GLenum, int literal(0), GLenum, int32, int32, int literal(0), GLenum, GLenum, ptr cuchar>
but expected one of: 
proc glTexImage2D(target: GLenum; level: GLint; internalformat: GLint; width: GLsizei;
                 height: GLsizei; border: GLint; format: GLenum; `type`: GLenum;
                 pixels: pointer): void
  first type mismatch at position: 3
  required type for internalformat: GLint
  but expression '6408'u' is of type: GLenum
```

* **What is the expected behavior?**
The code should compile. 

* **What is the motivation / use case for changing the behavior?**
I was able to work around them by declaring a local GL_LINEAR as a GLint with value 9729 and a local GL_RGBA as a GLint with value 6408 and passing them to these functions instead. 

I think that 

- either GL_LINEAR/GL_RGBA need to change to GLint or 
- the function signatures for glTexParameteri/glTexImage2D should accept GLenum.

* **Please tell us about your environment:**
  
  - Version: [ 1.0.0 ]
  - OS: [  MacOS  ]
  - Bindings: [ OpenGL | ImGui ]
  - Backend: [ C ] 
  - Nim Version: [1.0.0]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
suggestions how to fix, links for us to have context, eg. stackoverflow,
docs.gl, documentation etc)

**Comment by lmariscal** [comment]
Should be fixed be the recently pushed OpenGL loader change. Sorry for the delay.
