### ISSUE TITLE
Segfault in vkInit calling vkGetProcAddress

### ISSUE THREAD

**Issue by TinBryn** [nimgl/nimgl#33]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
segfaults

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**
```
import nimgl/vulkan
discard vkInit()
```

* **Please tell us about your environment:**
  
  - Version: 1.0.0 
  - OS:  Linux
  - Bindings: Vulkan 
  - Backend: C 

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
suggestions how to fix, links for us to have context, eg. stackoverflow,
docs.gl, documentation etc)

```
/home/kieran/.nimble/pkgs/nimgl-1.0.0/nimgl/vulkan.nim(9265) vkInit
/home/kieran/.nimble/pkgs/nimgl-1.0.0/nimgl/vulkan.nim(8694) vkLoad1_0
/home/kieran/.nimble/pkgs/nimgl-1.0.0/nimgl/vulkan.nim(29) :anonymous
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

* **Workaround**
deleting the line that causes the crash `result = vkGetProcAddress(procName)` leads to a fallback loading which works correctly.

**Comment by lmariscal** [comment]
After deleting that line, are the procedures loaded correctly? And if that line is giving a segfault is line 25 being called?

**Comment by lmariscal** [comment]
Also fixed by https://github.com/nimgl/nimgl/commit/82525e1015d965665bca01f3d333d8d88c08a39d if you can confirm that the procedures are loaded correctly.

**Comment by TinBryn** [comment]
I haven't gotten that far, but as far as I can tell, yes without that line I am able to create an instance and enumerate some extensions. I will test that change, but wrapping the code that I deleted in `when defined(windows)` should have the same effect.
