### ISSUE TITLE
Vulkan dylib not being set correctly

### ISSUE THREAD

**Issue by clive-g-brown** [nimgl/nimgl#34]
/.nimble/pkgs/nimgl-1.0.0/nimgl/vulkan.nim(20, 3) Error: unreachable statement after 'return' statement or '{.noReturn.}' proc

OSX.

**Comment by lmariscal** [comment]
I think it is fixed by https://github.com/nimgl/nimgl/commit/82525e1015d965665bca01f3d333d8d88c08a39d.
