### ISSUE TITLE
SIGSEGV error on windows

### ISSUE THREAD

**Issue by sl0burn** [nimgl/nimgl#36]
Testing imgui on windows with cimgui.dll built with mingw32-make.exe.

```
import imgui
igText("Hello World")
```
get below error.
```
Traceback (most recent call last)
c:\nim\imgui\main_imgui.nim(3) main_imgui
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
I think it is related to cimgui.dll - what is best way to build this.

**Comment by lmariscal** [comment]
Is your cimgui.dll built with Visual Studio and using the same architecture as your mingw?

**Comment by sl0burn** [comment]
No it is not build with visual studio.  It is built using the make file and mingw32 toolchain.

I did not see a .sln file for cimgui - do I have to create a solution file myself ?

**Comment by lmariscal** [comment]
You can use CMake to generate a Visual Studio project. Be sure to use the same architecture as your MinGW. The DLL must be built with Visual Studio.

**Comment by sl0burn** [comment]
Visual studio processed the makefile and I tried the dll from all these configurations (which are all msvc toolsets) but no luck so far. I am not 100% sure what mingw is using but i will try to find out.

![image](https://user-images.githubusercontent.com/2293241/69828170-0607bd00-11d8-11ea-86c2-348cc417e68c.png)
