### ISSUE TITLE
[glfw bug] Window content scale

### ISSUE THREAD

**Issue by adricoin2010** [nimgl/nimgl#43]
First of all, my English is pretty bad. My native language is Spanish.

I have only been able to test on windows, sorry.

I have encountered a problem with **Window content scale**. Both the **getWindowContectScale** function and its callback give wrong values.

Ex:
`Scale Window: x = 5.284266862267036e-315 y = 5.284266862267036e-315`

This functionality is very important to me. Neither SDL nor SFML implement it well, only GLFW.

I am using your library because it is the only one that is updated and works very well.

I leave here a small code for you to check and if it is possible to solve this problem. I have tested directly in C and have no problem and it shows the correct values.

```
import nimgl/glfw

assert glfwInit()

var window = glfwCreateWindow(300, 300, "Test Scale Window")
window.makeContextCurrent()

proc cb_scale_window(window: GLFWWindow, xscale, yscale : float) : void {.cdecl.} =
  echo "Callback -> Scale Window: \tx = ", xscale, "\ty = ", yscale

discard window.setWindowContentScaleCallback(cb_scale_window)

var x_scale, y_scale : float

while window.windowShouldClose() == false:
    glfwWaitEvents()
    window.getWindowContentScale(addr x_scale, addr y_scale)
    echo "Loop -> Scale Window: \tx = ", x_scale, "\ty = ", y_scale
    window.swapBuffers()
```
I have two monitors:
- 1080p scaled to 100%
- 4K scaled to 150%

This function, especially the callback, is to report the scale that the monitor has configured when the window changes from one monitor to another.

It can be checked even if you only have one monitor.

The results of the callback should be as follows:
```
100% -> 1.0
125% -> 1.25
150% -> 1.5
etc.
```

I've also tried defining glfwDLL to use the GLFW library that I have installed in MSYS2, but the same thing happens.

GLFW official documentation for Window Content Scale: [window_scale](https://www.glfw.org/docs/3.3/window_guide.html#window_scale)

- Version: nim 1.2.0 and nimgl 1.1.2
- OS: Windows 10 64 bits, 1909
- Binding: GLFW
- Backend: C

**Comment by lmariscal** [comment]
Yap, found the issue. It is that it should be using float32 instead of float.
Will be pushing a fix shortly

**Comment by lmariscal** [comment]
Pushed a fix, please let me know if it solves the issue for you so I can draft a release.

**Comment by adricoin2010** [comment]
Hello again, thanks for responding so quickly.

I have been testing the new version and it works perfectly.

Again, thank you very much.
