### ISSUE TITLE
Type mismatch with glGenVertexArrays and glGenBuffers

### ISSUE THREAD

**Issue by kzerot** [nimgl/nimgl#45]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
    glGenVertexArrays(1, some.addr)
    glGenBuffers(1, some.addr)

In current state you can only pass addr for one buffer/array. But in c++ you can pass also array of buffers

* **What is the current behavior?**
type mismatch: got <int literal(1), ptr seq[uint32]>
but expected one of: 
proc (n: GLsizei, arrays: ptr GLuint){.stdcall.}

* **What is the expected behavior?**

Possibility to pass arrays
var some = seq[uint32]
    glGenVertexArrays(5, some.addr)
    glGenBuffers(5, some.addr)

* **Please tell us about your environment:**
  
  - Version: [ 0.3.6 | 1.0.0 ]
  - OS: [ Linux ]
  - Bindings: [ OpenGL  ]
  - Backend: [ C ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
suggestions how to fix, links for us to have context, eg. stackoverflow,
docs.gl, documentation etc)

**Comment by lmariscal** [comment]
Due to the library being simple bindings without a wrapper around them, it requires it to be as close as possible to the C bindings. The way to pass a seq data type to a buffer is referencing the first item and getting the addr of it.
https://github.com/nimgl/nimgl/blob/master/examples/topengl.nim#L81 An example.

**Comment by lmariscal** [comment]
I agree that an OpenGL wrapper for Nim data types would be interesting, but currently out of the scope of this bindings.

**Comment by kzerot** [comment]
Thanks!
