### ISSUE TITLE
Compile error from nim cpp examples\timgui.nim

### ISSUE THREAD

**Issue by demotomohiro** [nimgl/nimgl#48]
I fixed this compile error with this PR but it is not merged to nimgl/nimgl repository.
https://github.com/nimgl/imgui/pull/2

* **I'm submitting a ...**
  - [*] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
I got compile error from backend g++ compiler
```
f:/project/nimgl/src/nimgl/private/cimgui/cimgui.h:1781:18: error: 'ImGuiSettingsHandler' was not declared in this scope
 1781 | typedef ImVector<ImGuiSettingsHandler> ImVector_ImGuiSettingsHandler;
      |                  ^~~~~~~~~~~~~~~~~~~~
f:/project/nimgl/src/nimgl/private/cimgui/cimgui.h:1781:38: error: template argument 1 is invalid
 1781 | typedef ImVector<ImGuiSettingsHandler> ImVector_ImGuiSettingsHandler;
      |                                      ^
f:/project/nimgl/src/nimgl/private/cimgui/cimgui.h:1783:18: error: 'ImGuiGroupData' was not declared in this scope
 1783 | typedef ImVector<ImGuiGroupData> ImVector_ImGuiGroupData;
      |                  ^~~~~~~~~~~~~~
```

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**
```
nim cpp examples\timgui.nim
```

* **Please tell us about your environment:**
  
  - Version: [ 1.1.3 ]
  - OS: [ Windows]
  - Bindings: [ OpenGL | GLFW | ImGui]
  - Backend: [ CPP ]

**Comment by lmariscal** [comment]
Yep, totally my bad. Sorry, and thank you for the notice.

**Comment by lmariscal** [comment]
Fixed by https://github.com/nimgl/nimgl/commit/57742e665b80338c274962ecffa1cdb5074a342f.

**Comment by lmariscal** [comment]
And released https://github.com/nimgl/nimgl/releases/tag/1.1.4, since I do believe this issue deserves a release.
Again, sorry on my mistake.
