### ISSUE TITLE
Wrong definion of glfwGetMonitors

### ISSUE THREAD

**Issue by kraptor** [nimgl/nimgl#54]
**Note: for support questions, please use stackoverflow or irc**. This
repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

Wrong function definition

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**

The definition of glfwGetMonitors makes the function uncallable, as an UncheckedArray[T] cannot be stored directly as a var/let variable. 

The current definiont of glfwMonitor should be like this, if not there is no way to call the function:
> proc glfwGetMonitors(count: ptr int32): ptr UncheckedArray[GLFWMonitor] {.importc: "glfwGetMonitors", cdecl.}

**Note the use of `ptr`**

* **Please tell us about your environment:**
  
  - Version: latest
  - OS: Windows
  - Bindings: GLFW
  - Backend: CPP

* **Other information** (e.g. detailed explanation, stacktraces, related issues,
suggestions how to fix, links for us to have context, eg. stackoverflow,
docs.gl, documentation etc)

**Comment by lmariscal** [comment]
Fixed by https://github.com/nimgl/glfw/commit/52a06d468ac8e5f6afaf92b4070973cb0fb6c58c, will push to main repo shortly.
