### ISSUE TITLE
Could not load cimgui.so Linux

### ISSUE THREAD

**Issue by pihentagy** [nimgl/nimgl#58]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note
  at the top of this template.

* **What is the current behavior?**

The example does not compile. After fixing the obvious issue it does not find `cimgui.so`.

Please advice how to obtain the shared object.

* **If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem**

```
~ ⌚ 20:56:24
$ nim r i.nim                                      
Hint: used config file '/home/pihentagy/.choosenim/toolchains/nim-1.4.0/config/nim.cfg' [Conf]
Hint: used config file '/home/pihentagy/.choosenim/toolchains/nim-1.4.0/config/config.nims' [Conf]
............CC: stdlib_system.nim
CC: .nimble/pkgs/imgui-1.78.0/imgui.nim
CC: i.nim

Hint:  [Link]
Hint: 36943 lines; 1.612s; 60.09MiB peakmem; Debug build; proj: /home/pihentagy/i.nim; out: /home/pihentagy/.cache/nim/i_d/i [SuccessX]
Hint: /home/pihentagy/.cache/nim/i_d/i  [Exec]
could not load: cimgui.so
(compile with -d:nimDebugDlOpen for more information)
Error: execution of an external program failed: '/home/pihentagy/.cache/nim/i_d/i '

~ ⌚ 20:56:37
$ 
```

The corrected example code
```nim
import imgui

igText("Hello World")

var f: ptr float32
igSliderFloat("float", f, 0.0f, 1.0f)
```

* **Please tell us about your environment:**
  
  - Version: nimgl@1.1.5, imgui@1.78
  - OS: Linux
  - Bindings: dunno how can I choose, could you point me to a readme or add relevant info to the readme?

**Comment by lmariscal** [comment]
Since ImGui is a C++ project to interact with it from the C backend we need a DLL. To generate a DLL I recommend using CMake and the official fork of cimgui https://github.com/nimgl/cimgui.

```bash
git clone --recursive https://github.com/nimgl/cimgui.git
cd cimgui
mkdir bld
cd bld
cmake ..
make # In case you are using Makefiles
```

If you followed the previous commands, there should be `cimgui.so` file, copy that file to your executable directory.

Please let me know if you have any other doubts.
